Code review
gapiyka/hermit pull request #3
Opened 2021-05-19 07:36 UTC by gapiyka

2021-05-29 20:03 UTC, tshemsedinov requested changes
- Refactor code duplication
- Use constants instead of magic numbers
- Use collections instead of `swith/case`
- Add eslint and prettier

2021-05-29 20:03 UTC, tshemsedinov commented on js/game.js
> +            modelCut = 120;
Magic numbers, use named constants or collection

2021-05-29 20:03 UTC, tshemsedinov commented on js/game.js
> +        ctx.drawImage(this.image, modelCut, 0, this.width, this.height, this.position.x - this.width / 2, this.position.y, 80, 40);
Long line, decompose, use intermediate variables

2021-05-29 20:03 UTC, tshemsedinov commented on js/game.js
> +        ctx.fillRect(this.position.x, this.position.y - 15, this.hp / 2.5, 10);
Magic numbers everywhere
![AmbitiousPracticalJabiru-small](https://user-images.githubusercontent.com/4405297/120083445-629baf00-c0d1-11eb-877a-73a416ed9fce.gif)

2021-05-29 20:03 UTC, tshemsedinov commented on js/game.js
> +                    break;
Use collection instead, see lectures about antipatterns and refactoring

2021-05-29 20:03 UTC, tshemsedinov commented on js/game.js
> +                    if (player.speed.y > 0) player.stopY();
Code duplication

2021-05-29 20:03 UTC, tshemsedinov commented on js/game.js
> +let ScoreRating = [];
Holly crap, mutable global scope
![WImtWKc](https://user-images.githubusercontent.com/4405297/120083515-d938ac80-c0d1-11eb-80fc-17e09021b5a5.gif)

2021-05-30 08:50 UTC, gapiyka commented
Fixed all except `mutable global scope` in next commit *main

![image](https://i.gifer.com/origin/ab/abc42d625dea3508f6c14bc41bb0f7db.gif)

2021-05-30 08:50 UTC, closed without merging

2021-05-30 09:01 UTC, tshemsedinov commented on js/game.js
> +        this.height = 40;
Magic numbers

2021-05-30 09:01 UTC, tshemsedinov commented on js/game.js
> +        };
Magic everywhere

2021-05-30 09:01 UTC, tshemsedinov commented on js/game.js
> +        this.lookRight = true;
```js
this.lookDirection = 'forward';
this.lookAngle = 'right';
```